version: '2'
services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  # for debugging
  alpine:
    image: alpine:latest
    hostname: alpine
    container_name: alpine
    command: sh
    tty: true
    stdin_open: true
